
ansible_user: sakthi
microk8s_channel: "latest/stable"
metallb_range: "192.168.1.100-192.168.1.150"

# --- Cloudflared config ---
cloudflared_arch_map:
  aarch64: "arm64"
  armv7l: "arm"
  x86_64: "amd64"
cloudflared_release_base: "https://github.com/cloudflare/cloudflared/releases/latest/download"

# --- Cloudflare tunnel IDs ---
# override these at runtime or set permanently here
tunnel1_id: "<TUNNEL_ID_1>"
tunnel2_id: "<TUNNEL_ID_2>"

cloudflare_tunnels:
  - name: sakthisaran
    cmd: "/usr/local/bin/cloudflared tunnel --no-autoupdate run {{ tunnel1_id }}"
  - name: techtriohub
    cmd: "/usr/local/bin/cloudflared tunnel --no-autoupdate run {{ tunnel2_id }}"

repo_url: "https://github.com/yourusername/yourrepo.git"  # ğŸ” change this
repo_dir: "/tmp/ghost_restore"                            # temp clone dir